<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- 禁用 CS8603 警告：MappingExpression 方法永远不会返回 null -->
    <NoWarn>$(NoWarn);CS8603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ling.Mapper.csproj" />
  </ItemGroup>

</Project>
