<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- 包版本 -->
		<Version>1.1.3</Version>


		<!-- 多目标框架 -->
		<TargetFrameworks>net6.0;net8.0;net9.0;net10.0</TargetFrameworks>

		<!-- 编译配置 -->
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- 设置源代码编码为 UTF-8，解决中文注释乱码问题 -->
		<Utf8Output>true</Utf8Output>
		<LangVersion>latest</LangVersion>

		<!-- 文档 -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\Ling.Mapper.xml</DocumentationFile>

		<!-- 元数据（NuGet） -->
		<PackageId>Ling.Mapper</PackageId>
		<Authors>yanhuuo</Authors>
		<Company>Mapper</Company>
		<Description>轻量级 Fluent 风格对象映射器（Fluent Object Mapper），支持多层级映射、链式 API、AOT、DI 注入、运行时映射规则配置。</Description>

		<!-- 仓库地址（建议用 GitHub） -->
		<RepositoryUrl>https://github.com/yanhuuo/Ling.Mapper</RepositoryUrl>
		<PackageProjectUrl>https://github.com/yanhuuo/Ling.Mapper</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>

		<!-- 许可证 -->
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<!-- NuGet 图标 -->
		<PackageIcon>ling.png</PackageIcon>

		<!-- README（NuGet 搜索必备） -->
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<!-- Tag 提升 NuGet 搜索曝光 -->
		<PackageTags>mapper;map;fluent;automapper;object-mapper;AOT;DI;adapt</PackageTags>

		<!-- 构建时是否自动打包（CI 用 false 正确） -->
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<!-- 打包图标 -->
		<None Include="ling.png" Pack="true" PackagePath="" />

		<!-- 打包 README -->
    <None Include="..\README.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup><!-- 依赖：使用条件版本以兼容不同的 .NET 框架 -->
		<!--<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" Condition="'$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net10.0'" />-->
	
	  <Folder Include="IMapper\" />
	</ItemGroup>

</Project>
